# fly.toml app configuration file generated for k6-parse on 2023-10-17T13:39:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "k6-parse"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
